<div class="title">
	<table cellspacing="0" cellpadding="0">
		<tr height="35px">
			<td width="10px"></td>
			<td><a href="index.html"><img src="logo.png" height="30px"></a></td>
			<td width="10px"></td>
			<td><h1>Quản lý công việc</h1></td>
			<td width="10px"></td>
			<td>
				<select>
					<option>Tất cả các công việc</option>
					<option>Các công việc chưa hoàn thành</option>
					<option>Các công việc đã hoàn tất</option>
				</select>
			</td>
			<td width="10px"></td>
			<td><div class="button">Thêm công việc</div></td>
		</tr>
	</table>
</div>
